### ISSUE TITLE
Add Milvus

### ISSUE THREAD

**Issue by erikbern** [erikbern/ann-benchmarks#140]
https://github.com/milvus-io/milvus

"Milvus -- the world's fastest vector search engine." would love to verify that claim :)

**Comment by RyanWei** [comment]
Hey Erik, 

I am from Milvus team:) Big fan. Much appriaciate your work in ANN, really helped us a lot when we build Milvus. We are honored that you noticed our work and look forward to your verification. 

We'd love to talk more and assist the test if needed, let us know:)

Regards,
Ryan

**Comment by erikbern** [comment]
@RyanWei take a look at #149!

**Comment by cxie** [comment]
Hi Erik, 

I am Starlord from the Milvus team. Firstly, we would be happy to have Milvus listed in your new benchmark. We really appreciate all your time and efforts. Regarding Milvus benchmarking, we opened another PR, #153. We recommend you use the '"insert a vector with id" API for Milvus tests, as you did in other ANNS tests. 
![mnist-784-euclidean_10_euclidean](https://user-images.githubusercontent.com/653101/75986431-0aefb180-5f29-11ea-9e9c-a8f0f1565aa2.png)
![mnist-784-euclidean_10_euclidean](https://user-images.githubusercontent.com/653101/75986497-25298f80-5f29-11ea-8bcb-044bf6749164.png)

As a vector similarity search engine server, Milvus is designed for easy to use, high reliability, easy to scale, and high performance. Milvus supports near real-time search, CRUD, WAL, data consistency, distributed deployment, high availability, and much more. However, nothing good comes without a price. A fixed amount of server processing time, usually ~1 ms, will be added to each similarity search query, so the upper bond QPS of a single Milvus server instance would be around 1K. This was confirmed in both your benchmark results and our results (with some minor discrepancies, which I will discuss later). Milvus will perform much better in batch query mode and async single query mode because the ~1ms server processing time will be prorated among queries and become insignificant.

Back to Milvus benchmarking, we've run your ann-benchmarks code on an AWS EC2 c5.4xlarge instance to follow exactly the same route that you tested. We found out there are some discrepancies between your results and our results. Our plot of mnist-784-euclidean_10_euclidean results is capping out at about 770 QPS while yours is capping out at about 350 QPS. Moreover, our plot of glove-25-angular_10_angular results is capping out at about 900 QPS (very close to the theoretical upper bond mentioned above) while yours is capping out at about 400 QPS. We attached our plots and full results package for your further investigation. 

Lastly, Milvus is positioned as an open source vector similarity search engine built on top of various ANNS algorithms. We are actively working on the support of more algorithms so that Milvus can better fit into different requirements and scenarios. We have planned to support Annoy and HNSW in Milvus 0.8.0 (April 2020). We may appreciate a new benchmark test on 0.8.0 after its release or when you think it's appropriate.   

![mnist-784-euclidean_10_euclidean](https://user-images.githubusercontent.com/653101/75986561-44c0b800-5f29-11ea-9ad7-ad3ad180336b.png)
![glove-25-angular_10_angular](https://user-images.githubusercontent.com/653101/75986585-51451080-5f29-11ea-82fd-5c2ba8a21db5.png)
[milvus_EC2_c5.4xlarge_results.zip](https://github.com/erikbern/ann-benchmarks/files/4293170/milvus_EC2_c5.4xlarge_results.zip)
