### ISSUE TITLE
Installation fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by hairbeRt** [erikbern/ann-benchmarks#190]
Installing via python3 fails running installation.py, because the request 'https://raw.githubusercontent.com/milvus-io/docs/v0.6.0/assets/server_config.yaml'' returns 404. The repo structure of milvus-io/docs has changed, URL should be changed to 'https://raw.githubusercontent.com/milvus-io/docs/master/v0.6.0/assets/server_config.yaml'. Possibly that once this is fixed, some other URLs from the same repo might be broken.

**Comment by erikbern** [comment]
ok, i think the milvus setup is pretty old and we should update it to the latest version

**Comment by stephenleo** [comment]
Apparently, after the milvus link was updated, it still fails on Ubuntu at pynndescent. I'll push a fix later.

I'm also thinking of updating `install.py` so that if a particular algo fails, the installation still continues and just logs which algos failed and which passed. In this way, we won't face a completely failed installation if just one or two package fails. what do you think?

**Comment by erikbern** [comment]
I think that makes sense. Also the Milvus implementation right now is pretty bad. It's a really old version and it's a bit fragile how it's set up. I'm OK disabling/removing it for now.
