### ISSUE TITLE
Using custom metrics

### ISSUE THREAD

**Issue by Chokerino** [erikbern/ann-benchmarks#242]
Hello,

I wanted to use NN approximation for a problem and I need to use a custom metric for distance calculation between 2 data points. As per my understanding, I would need to implement the algorithm on my own and no library provides such support for adding my own distance score? My problem is related to genomes and the distance between 2 genomes is calculated by an in-house program. Also, to find the best algorithm would require me to test them out rather than only choosing say top 3 because as per my understanding NN search algorithm performance varies with datasets and dimensions. Any help/advice would be appreciated.

**Comment by maumueller** [comment]
We benchmark NN approaches and do not develope them, but my suggestion is to look at some of the graph-based approaches. Personally, I think https://github.com/lmcinnes/pynndescent is a good starting point, see e.g., https://github.com/lmcinnes/pynndescent/commit/56a16eb6bd5ea954c5aa7906a1587b386d29e5d0 for adding a new distance.

It will be quite some work to "test out multiple different implementations" because you need to customize the individual implementations. I would rather start with one and see whether it's performance/quality is sufficient in your use case. 

Adding @searchivarius because he probably has much more to say about that :-)

**Comment by erikbern** [comment]
Closing this for now as it doesn't seem related to ann-benchmarks per se!
