### ISSUE TITLE
relax the timeout setting to 24 hours for better qps-recall performance

### ISSUE THREAD

**Issue by WPJiang** [erikbern/ann-benchmarks#374]
@erikbern , would you please consider relaxing the timeout setting to 24 hours? We found that for some datasets, some algorithms (such as NGTqg and qsgNGT) cannot finish the index building stage within 2 hours, but when the timeout is set to 24 hours, they dould get very good qps-recall performance. Of course, these algorithms’ disadvantage in building time will be reflected in the Recall-build time performance. 24 hours of construction time is indeed a bit long, but for some offline construction applications, it is acceptable to trade construction time for qps-recall performance.

**Comment by erikbern** [comment]
I don't think it's worth doing since

1. IMO this seems a bit impractical – if it takes 24h to build an index, it's only going to be useful in very limited applications, and I think it would create a misrepresentation when presenting the results
2. It would cause the benchmarks to take a lot longer to run. I was able to run all benchmarks in about 12h on an r6.16xlarge at a cost of about $50 (for one dataset). But if we increase the timeouts to 24h then I expect the total runtime of the benchmarks to go up to several days or maybe a week – it will be much harder to run everything and it might cost $500 instead of $50
3. Related to the previous point, there have been some misbehaving algorithms that crash into an infinite loop and just get stuck. So the 2h time limit makes sure we're not wasting time waiting for an algorithm that will never finish.

2h is obviously a completely arbitrary limit, but I think it's reasonable in practice – it keeps the cost of benchmarks below $100 per dataset, and it makes it practical to run in 6-12h on a big machine.

**Comment by WPJiang** [comment]
I understand your concern,thanks for your patient answer
