### ISSUE TITLE
Use of multiple CPUs for index building

### ISSUE THREAD

**Issue by masajiro** [erikbern/ann-benchmarks#381]
Thank you for such excellent benchmarks. 
As for #374, I agree that the 2 h timeout is reasonable in practical use. However, I don't think that using only one CPU for building indices is reasonable in practical use. Would it be possible to use multiple CPUs for building them like [big-ann-benchmarks](https://github.com/harsha-simhadri/big-ann-benchmarks)?

**Comment by maumueller** [comment]
I second Erik's thoughts on this. I was in favor of such a setup as well, but I like the current way of parallelizing running the benchmark. We do it differently in the big-ann-benchmarks project because it is completely unfeasible to build single-threaded on billion-scale.

To add a thought on the docker core limitations: I think in most application we would be able to set/reset the number of threads used internally, but then all trust is put into the implementation and it might be difficult to audit.

**Comment by erikbern** [comment]
The question of threads keeps coming up so I might add a section in the readme to explain the rationale for single threaded benchmarks

**Comment by masajiro** [comment]
Thank you for your answers. I understand why you want to finish the benchmark as soon as possible because it costs a lot of money. When I want the result of a benchmark with a longer timeout, I will try to run it myself and publish the result.
