### ISSUE TITLE
how to clean the older benchmark runs

### ISSUE THREAD

**Issue by pauldintel** [erikbern/ann-benchmarks#468]
I do see bunch of png and html file generated and also the previous runs keep in history .
How to purge the older runs and make sure any benchmark starts clean ? 
Also any way to make sure the html and png generated into a dedicated folder rather messing up the root /ann_benchmark folder ?
thanks

**Comment by maumueller** [comment]
You probably see these because of something that you did. It would have been helpful to know which commands you invoked. 

You can use `--force` while invoking `run.py` to overwrite the results files, even easier would be to just remove the files the are present in `results/`. The "bunch of png and html file" is probably the result of invoking `create_website.py`. You can specify an `--outputdir`, as mentioned in the README.

**Comment by pauldintel** [comment]
great input thanks you @maumueller  . found them and working
